name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "261c5466debb4231b549f7bfec218da9" },
  { binding = "SHARE", id = "70dd036dc3ce493bbfd9609e48873c1f" }
]